name: build
on:
  push:
    branches:
      - fix-1011
    
jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14


      - uses: engineerd/setup-kind@v0.1.0

      - name: Testing
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl get nodes
          echo ">>> delete KIND's default storageclass"
          kubectl delete storageclass standard || true
          echo ">>> deploy hostpath provisioner"
          kubectl apply -n kube-system -f ${GITHUB_WORKSPACE}/definitions/github/hostpath-provisioner.yaml
          echo ">>> run pod"
          kubectl apply -f ${GITHUB_WORKSPACE}/hack/definitions/github/hostpath-provisioner-pod.yaml
          sleep 30
          kubectl logs -n kube-system -lapp.kubernetes.io/name=hostpath-provisioner
          sleep 30
          echo ">>> describe pod"
          kubectl describe pod -n default volume-test
          sleep 10
          echo ">>> show pod logs"
          kubectl logs -n default volume-test
          sleep 30
          echo ">>> describe pod"
          kubectl get pods -n default
          kubectl describe pod -n default volume-test
          kubectl get pvc
          kubectl get pv

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint  ./charts/kyverno/

      - name: Create Namespace
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"create namespace kyverno"'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: install kyverno --namespace kyverno ./charts/kyverno





