name: build
on:
  push:
    branches:
      - 'fix-1011'
  pull_request:

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name : binary build & kustomize
        run: |
           make ci 

      - name: e2e testing
        run: |
          cat ${GITHUB_WORKSPACE}/definitions/install.yaml
          echo ">>> Install Kyverno"
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/install.yaml
          cat ${GITHUB_WORKSPACE}/definitions/install.yaml
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/github/rbac.yaml
          sleep 60

          echo ">>> Run Kyverno e2e test"
          make test-e2e






