name: build
on:
  push:
    branches:
      - 'fix-1011'
  pull_request:

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && \
              chmod a+x kustomize && \
              make ci
      -
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
          repository: "evalsocket/kyverno"
          tag_with_ref: true
          push: ${{ github.event.pull_request.head.sha }}
          dockerfile : cmd/kyverno/Dockerfile
          path: .

      -
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
          repository: "evalsocket/kyvernopre"
          tag_with_ref: true
          push: ${{ github.event.pull_request.head.sha }}
          dockerfile : cmd/initContainer/Dockerfile
          path: .

      - uses: engineerd/setup-kind@v0.1.0

      - name: Testing
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl get nodes
          echo ">>> delete KIND's default storageclass"
          kubectl delete storageclass standard || true
          echo ">>> deploy hostpath provisioner"
          kubectl apply -n kube-system -f ${GITHUB_WORKSPACE}/definitions/github/hostpath-provisioner.yaml
          echo ">>> run pod"
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/github/hostpath-provisioner-pod.yaml

          echo ">>> Install Kyverno"
          kubectl apply -f ${GITHUB_WORKSPACE}/definitions/install.yaml
          sleep 60

          echo ">>> Run Kyverno e2e test"
          make test-e2e






